// Package v1 defines the cluster RPC protocol for TokMesh.
//
// This protocol is used for internal cluster communication only,
// using Connect + Protobuf over mTLS.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: cluster.proto

package clusterv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/yndnr/tokmesh-go/api/proto/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ClusterServiceName is the fully-qualified name of the ClusterService service.
	ClusterServiceName = "tokmesh.cluster.v1.ClusterService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ClusterServiceJoinProcedure is the fully-qualified name of the ClusterService's Join RPC.
	ClusterServiceJoinProcedure = "/tokmesh.cluster.v1.ClusterService/Join"
	// ClusterServiceGetShardMapProcedure is the fully-qualified name of the ClusterService's
	// GetShardMap RPC.
	ClusterServiceGetShardMapProcedure = "/tokmesh.cluster.v1.ClusterService/GetShardMap"
	// ClusterServiceTransferShardProcedure is the fully-qualified name of the ClusterService's
	// TransferShard RPC.
	ClusterServiceTransferShardProcedure = "/tokmesh.cluster.v1.ClusterService/TransferShard"
	// ClusterServicePingProcedure is the fully-qualified name of the ClusterService's Ping RPC.
	ClusterServicePingProcedure = "/tokmesh.cluster.v1.ClusterService/Ping"
)

// ClusterServiceClient is a client for the tokmesh.cluster.v1.ClusterService service.
type ClusterServiceClient interface {
	// Join adds the node to the cluster.
	Join(context.Context, *connect.Request[v1.JoinRequest]) (*connect.Response[v1.JoinResponse], error)
	// GetShardMap returns the current shard map snapshot.
	GetShardMap(context.Context, *connect.Request[v1.GetShardMapRequest]) (*connect.Response[v1.GetShardMapResponse], error)
	// TransferShard streams shard migration data (rebalance).
	TransferShard(context.Context) *connect.ClientStreamForClient[v1.TransferShardRequest, v1.TransferShardResponse]
	// Ping checks if a node is alive.
	Ping(context.Context, *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error)
}

// NewClusterServiceClient constructs a client for the tokmesh.cluster.v1.ClusterService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewClusterServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ClusterServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	clusterServiceMethods := v1.File_cluster_proto.Services().ByName("ClusterService").Methods()
	return &clusterServiceClient{
		join: connect.NewClient[v1.JoinRequest, v1.JoinResponse](
			httpClient,
			baseURL+ClusterServiceJoinProcedure,
			connect.WithSchema(clusterServiceMethods.ByName("Join")),
			connect.WithClientOptions(opts...),
		),
		getShardMap: connect.NewClient[v1.GetShardMapRequest, v1.GetShardMapResponse](
			httpClient,
			baseURL+ClusterServiceGetShardMapProcedure,
			connect.WithSchema(clusterServiceMethods.ByName("GetShardMap")),
			connect.WithClientOptions(opts...),
		),
		transferShard: connect.NewClient[v1.TransferShardRequest, v1.TransferShardResponse](
			httpClient,
			baseURL+ClusterServiceTransferShardProcedure,
			connect.WithSchema(clusterServiceMethods.ByName("TransferShard")),
			connect.WithClientOptions(opts...),
		),
		ping: connect.NewClient[v1.PingRequest, v1.PingResponse](
			httpClient,
			baseURL+ClusterServicePingProcedure,
			connect.WithSchema(clusterServiceMethods.ByName("Ping")),
			connect.WithClientOptions(opts...),
		),
	}
}

// clusterServiceClient implements ClusterServiceClient.
type clusterServiceClient struct {
	join          *connect.Client[v1.JoinRequest, v1.JoinResponse]
	getShardMap   *connect.Client[v1.GetShardMapRequest, v1.GetShardMapResponse]
	transferShard *connect.Client[v1.TransferShardRequest, v1.TransferShardResponse]
	ping          *connect.Client[v1.PingRequest, v1.PingResponse]
}

// Join calls tokmesh.cluster.v1.ClusterService.Join.
func (c *clusterServiceClient) Join(ctx context.Context, req *connect.Request[v1.JoinRequest]) (*connect.Response[v1.JoinResponse], error) {
	return c.join.CallUnary(ctx, req)
}

// GetShardMap calls tokmesh.cluster.v1.ClusterService.GetShardMap.
func (c *clusterServiceClient) GetShardMap(ctx context.Context, req *connect.Request[v1.GetShardMapRequest]) (*connect.Response[v1.GetShardMapResponse], error) {
	return c.getShardMap.CallUnary(ctx, req)
}

// TransferShard calls tokmesh.cluster.v1.ClusterService.TransferShard.
func (c *clusterServiceClient) TransferShard(ctx context.Context) *connect.ClientStreamForClient[v1.TransferShardRequest, v1.TransferShardResponse] {
	return c.transferShard.CallClientStream(ctx)
}

// Ping calls tokmesh.cluster.v1.ClusterService.Ping.
func (c *clusterServiceClient) Ping(ctx context.Context, req *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error) {
	return c.ping.CallUnary(ctx, req)
}

// ClusterServiceHandler is an implementation of the tokmesh.cluster.v1.ClusterService service.
type ClusterServiceHandler interface {
	// Join adds the node to the cluster.
	Join(context.Context, *connect.Request[v1.JoinRequest]) (*connect.Response[v1.JoinResponse], error)
	// GetShardMap returns the current shard map snapshot.
	GetShardMap(context.Context, *connect.Request[v1.GetShardMapRequest]) (*connect.Response[v1.GetShardMapResponse], error)
	// TransferShard streams shard migration data (rebalance).
	TransferShard(context.Context, *connect.ClientStream[v1.TransferShardRequest]) (*connect.Response[v1.TransferShardResponse], error)
	// Ping checks if a node is alive.
	Ping(context.Context, *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error)
}

// NewClusterServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewClusterServiceHandler(svc ClusterServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	clusterServiceMethods := v1.File_cluster_proto.Services().ByName("ClusterService").Methods()
	clusterServiceJoinHandler := connect.NewUnaryHandler(
		ClusterServiceJoinProcedure,
		svc.Join,
		connect.WithSchema(clusterServiceMethods.ByName("Join")),
		connect.WithHandlerOptions(opts...),
	)
	clusterServiceGetShardMapHandler := connect.NewUnaryHandler(
		ClusterServiceGetShardMapProcedure,
		svc.GetShardMap,
		connect.WithSchema(clusterServiceMethods.ByName("GetShardMap")),
		connect.WithHandlerOptions(opts...),
	)
	clusterServiceTransferShardHandler := connect.NewClientStreamHandler(
		ClusterServiceTransferShardProcedure,
		svc.TransferShard,
		connect.WithSchema(clusterServiceMethods.ByName("TransferShard")),
		connect.WithHandlerOptions(opts...),
	)
	clusterServicePingHandler := connect.NewUnaryHandler(
		ClusterServicePingProcedure,
		svc.Ping,
		connect.WithSchema(clusterServiceMethods.ByName("Ping")),
		connect.WithHandlerOptions(opts...),
	)
	return "/tokmesh.cluster.v1.ClusterService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ClusterServiceJoinProcedure:
			clusterServiceJoinHandler.ServeHTTP(w, r)
		case ClusterServiceGetShardMapProcedure:
			clusterServiceGetShardMapHandler.ServeHTTP(w, r)
		case ClusterServiceTransferShardProcedure:
			clusterServiceTransferShardHandler.ServeHTTP(w, r)
		case ClusterServicePingProcedure:
			clusterServicePingHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedClusterServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedClusterServiceHandler struct{}

func (UnimplementedClusterServiceHandler) Join(context.Context, *connect.Request[v1.JoinRequest]) (*connect.Response[v1.JoinResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tokmesh.cluster.v1.ClusterService.Join is not implemented"))
}

func (UnimplementedClusterServiceHandler) GetShardMap(context.Context, *connect.Request[v1.GetShardMapRequest]) (*connect.Response[v1.GetShardMapResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tokmesh.cluster.v1.ClusterService.GetShardMap is not implemented"))
}

func (UnimplementedClusterServiceHandler) TransferShard(context.Context, *connect.ClientStream[v1.TransferShardRequest]) (*connect.Response[v1.TransferShardResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tokmesh.cluster.v1.ClusterService.TransferShard is not implemented"))
}

func (UnimplementedClusterServiceHandler) Ping(context.Context, *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tokmesh.cluster.v1.ClusterService.Ping is not implemented"))
}
